  version: '3.7'

  services:
    db:
      image: postgres:12-alpine
      env_file:
        - ./.env
      expose:
        - "5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data/

    rabbitmq:
      image: rabbitmq:alpine
      expose:
        - 5672

    celery:
        build: .
        command: celery -A theeye worker -l info
        volumes:
          - code:/app
        expose:
          - 8001
        env_file:
          - ./.env
        depends_on:
          - rabbitmq

    web:
      build: .
      command: gunicorn theeye.wsgi:application --bind 0.0.0.0:8001
      volumes:
        - static_volume:/app/staticfiles
      expose:
        - 8001
      depends_on:
        - db
      env_file:
        - ./.env
      entrypoint:
        - "./docker-entrypoint.sh"

    nginx:
      build: ./deploy/nginx
      volumes:
        - static_volume:/app/staticfiles
      expose:
        - 8002
      depends_on:
        - web
      ports:
        - "8002:8002"

  volumes:
    postgres_data:
    static_volume:
    code: